@host = https://localhost
@port = 7237
@token = CfDJ8N_g_kqWmplNik__Rv_doJ4uI8qdWcA32Uzbqx2hFqWrTQbJnGWP4p2VKVEhJ7n2d2TK0dPQjPyyH5ZMaAoO6TlZrXUyW81j3LZHzrJiFxyErN8N6PKd6FYI5NHqjr4Toc4G8jylyoNOjDLX1nhhSUNjaBtm2-yITn0airxpQ4FZTJ4SzpsfQt9a2EfXZZpOogdO9P08Dgu8m_Thqn0KCAFEyLowE4IHeRLR56h7dfn7Lr31uXD4M-FYW2ODgJvRMYQyIwSqOgujDjmw4hEISn9Zc2OU_47DoPphmiH1mx97z2YtbpCQ1kEecpdqbVWVuQQjcSbgVKlN_kelICJ61P_FKGfK7LYpSpOy652EQ92HCMlC-NWSoNb-YX5QdCCzlTtkqjuxpnJSJRty19PGpz2gtxAzzGkT5o1_MXoSo0ZnlW3FvAqBhjex68MGRr8ZkY26rC58IEWp6itBVMYVYbMwd1Jm75dDkUcjAEFcQiJO6CndPOOmLVUkgp8EuEdGsAMEK3MN5U5y_IY3cqaP6jqmNZqTX-TLGP8mAzH6fmVeS_zI7sjmUMQAoc5Ohko_glu6VWLSvZq_Z6vJVno9Ob5IiqoVZIPYi1v2H5KsQeM1F03hKDQxt8XqQX8PTFg0zQarAv9DLcmFSh2Ry1Dh7LFUgLDFwcF6Lyn9wwzuTpDdylpe-oo4VWJZMRd2-ZuNlg

@Restaurant.API_HostAddress = https://localhost:7237


GET {{Restaurant.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=10&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}


###

GET {{Restaurant.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}


GET {{Restaurant.API_HostAddress}}/api/restaurants/6
###

POST {{Restaurant.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
     "Name": "Tasty Bites56",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}
###
DELETE {{Restaurant.API_HostAddress}}/api/restaurants/6
###
GET https://localhost:7237/api/restaurants/3

###
PATCH {{Restaurant.API_HostAddress}}/api/restaurants/3
Content-Type: application/json
{
  "Name": "Sample patch",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}

###
POST {{Restaurant.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json
{
  "Name": "Spaghetti Rome",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 0
}

###
GET https://localhost:7237/api/restaurants/3/dishes
###
DELETE {{Restaurant.API_HostAddress}}/api/restaurants/3/dishes

###
POST {{Restaurant.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
    "email": "owner@test.com",
    "password": "Password1!"
}

###
POST {{Restaurant.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
     "email": "owner@test.com",
    "password": "Password1!"
}

###
POST {{Restaurant.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
    "email": "testuser@test.com",
    "password": "Password1!"
}

###
PATCH {{Restaurant.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}
###
POST {{Restaurant.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}
###