@host = https://localhost
@port = 7237

@Restaurant.API_HostAddress = https://localhost:7237


GET {{Restaurant.API_HostAddress}}/api/restaurants

###
GET {{Restaurant.API_HostAddress}}/api/restaurants/6
###

POST {{Restaurant.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
     "Name": "Tasty Bites56",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}
###
DELETE {{Restaurant.API_HostAddress}}/api/restaurants/6
###
GET https://localhost:7237/api/restaurants/3

###
PATCH {{Restaurant.API_HostAddress}}/api/restaurants/3
Content-Type: application/json
{
  "Name": "Sample patch",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}

###
POST {{Restaurant.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json
{
  "Name": "Spaghetti Rome",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 0
}

###
GET https://localhost:7237/api/restaurants/3/dishes
###
DELETE {{Restaurant.API_HostAddress}}/api/restaurants/3/dishes